options:
  # Don't merge default rules
  merge-default-rules: true

files:
  include:
  - 'assets/sass/**/*.scss'
  - 'assets/sass/*.scss'

# Rule Configuration
rules:
  clean-import-paths: 2
  extends-before-mixins: 2
  extends-before-declarations: 2
  border-zero: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  no-css-comments: 0
  no-ids: 2
  no-important: 2
  no-color-literals: 1
  single-line-per-selector: 2
  hex-length:
    - 2
    - style: long
  nesting-depth:
    - 2
    - max-depth: 2
  hex-notation:
    - 2
    - style: lowercase
  indentation:
    - 2
    - size: 4
  shorthand-values:
    - 2
    - allowed-shorthands:
      - 1
      - 2
  quotes:
      - 2
      - style: single
  property-sort-order:
    - 2
    - ignore-custom-properties: false
  no-vendor-prefixes:
    - 2
    - properties:
        - content
    - 'additional-identifiers':
      - 'khtml'
      - 'o'
  # I don't agree -- Roelof
  class-name-format: 0
  variable-name-format: 0
